version: '3.4'
services:
  congestion_cargo:
    build: .
    container_name: congestion_cargo
    ports:
      - "8085:8085"
    volumes:
      - .:/home/project
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.8
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 192.168.0.1/24
